version: 1
type: "single"
worker:
  container: "tensorflow/tensorflow:1.13.1-gpu-py3"
  command: "pip install -r requirements.txt && python mnist.py"
  machine-type: "K80"
model:
  type: Tensorflow
  path: '/artifacts'
checks:
  tensorflow:loss:
    target: 0.0..1.0
    aggregate: max
  tensorflow:accuracy:
    target: 0.85..1.000
    aggregate: median
  defaults:
    precision: 3
