version: 1


type: "multi-grpc"
ports: "5000"

parameter-server:
  container: "tensorflow/tensorflow:1.13.1-gpu-py3"
  command: "python mnist.py"
  machine-type: "K80"
  count: 1
worker:
  container: "tensorflow/tensorflow:1.13.1-gpu-py3"
  command: "python mnist.py"
  machine-type: "K80"
  count: 2
  
